server:
  port: 8011
spring:
  application:
    name: ch4-1-gzip
logging:
  level:
    cn.springcloud.book.feign.service.HelloFeignService:
      debug

feign:
  compression:
    request:
      enabled: true
      mime-type: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enable: true
