server:
  port: 10002
eureka:
  instance:
    metadata-map.zone: zone3
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-west
    service-url:
      zone1: http://localhost:8763/eureka/
      zone2: http://lcoalhost:8764/eureka/
    availability-zones:
      region-east: zone3,zone4
