server:
  port: 8012
spring:
  application:
    name: ch4-5-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true

